name = "transfer"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.14"
module_path = "github.com/your/module/name"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/your/module/name"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "pick_role"
instances = { min = 2, max = 100, default = 2 }

  [testcases.params]
  clients   = { type = "int", default = 1 }
  providers = { type = "int", default = 1 }
  role      = { type = "string" }
  
[[testcases]]
name = "duo_role"
instances = { min = 2, max = 100, default = 2 }

  [testcases.params]
  role = { type = "string" }

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
