name = "testplans"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.16"
module_path = "github.com/myelnet/pop/testplans"
exec_pkg = "."
enable_go_build_cache = true

[builders."exec:go"]
enabled = true
module_path = "github.com/myelnet/pop/testplans"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[global.build_config]
enable_go_build_cache = true

[[testcases]]
name= "routing_gossip"
instances = { min = 3, max = 420, default = 3 }

  [testcases.params]
  providers = { type = "int", default = 1 }
  regions = { type = "array", default = ["Global"] }
  bootstrap = { type = "int" , default = 1 }
  min_conns = { type = "int", default = 20 }
  max_conns = { type = "int", default = 40 }
  min_latency = { type = "duration", default="50ms" }
  max_latency = { type = "duration", default="300ms" }
  min_jitter = { type = "duration", default="30ms" }
  max_jitter = { type = "duration", default="50ms" }
  min_bandwidth = { type = "int", default="500000" }
  max_bandwidth = { type = "int", default="10000000" }

[[testcases]]
name= "replication_dispatch"
instances = { min = 1, max = 100, default = 6 }

  [testcases.params]
  providers = { type = "int", default = 1 }
  regions = { type = "array", default = ["Global"] }
  bootstrap = { type = "int", default = 1 }
  min_conns = { type = "int", default = 20 }
  max_conns = { type = "int", default = 40 }

# Replication bootstrap tests the process of new peers retrieving popular content
# when joining the network
[[testcases]]
name = "replication_bootstrap"
instances = { min = 3, max = 300, default = 3 }

  [testcases.params]
  regions = { type = "array", default = ["Global"] }
  bootstrap = { type = "int", default = 1 }
  providers_1 = { type = "int", default = 1 }
  providers_2 = { type = "int", default = 1 }
  min_conns = { type = "int", default = 20 }
  max_conns = { type = "int", default = 40 }
  tx_per_provider = { type = "int", default = 1 }
