[metadata]
  name = "base_pick_role"

[global]
  plan = "transfer"
  case = "pick_role"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  clients = "1"
  providers = "1"

[[groups]]
  id = "providers"
  [groups.instances]
    count = 1
  [groups.run]
    [groups.run.test_params]
      role = "provider"

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
  [groups.run]
    [groups.run.test_params]
      role = "client"

