[metadata]
  name = "single_content_copy"

[global]
  plan = "discovery"
  case = "gossip"
  total_instances = 4
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  clients = "1"
  providers = "3"
  replication = "1"
  bootstrap = "0"
  regions = '["Global"]'
  conn_per_peer = "2"

[[groups]]
  id = "bootstrap"
  [groups.instances]
    count = 0

[[groups]]
  id = "providers"
   [groups.instances]
    count = 3

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
