[metadata]
  name = "baseline"

[global]
  plan = "testplans"
  case = "replication_dispatch"
  total_instances = 10
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  regions = '["Global"]'
  bootstrap = "6"
  providers = "10"

[[groups]]
  id = "providers"
  [groups.instances]
    count = 9

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1

