[metadata]
  name = "high_content_replication"

[global]
  plan = "pop"
  case = "routing_gossip"
  total_instances = 40
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  regions = '["Global"]'
  bootstrap = "10"
  providers = "8"

[[groups]]
  id = "bystanders"
    [groups.instances]
    count = 31

[[groups]]
  id = "providers"
   [groups.instances]
    count = 8

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
