[metadata]
  name = "low_content_replication"

[global]
  plan = "testplans"
  case = "routing_gossip"
  total_instances = 40
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  regions = '["Global"]'
  bootstrap = "10"
  providers = "1"

[[groups]]
  id = "bystanders"
    [groups.instances]
    count = 38

[[groups]]
  id = "providers"
   [groups.instances]
    count = 1

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
