name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Sync Submodule
      run: |
        git submodule sync
        git submodule update --init

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Linux deps
      run: |
        sudo apt-get update
        sudo apt-get install ocl-icd-opencl-dev

    - name: FFI build
      run: make -C ./extern/filecoin-ffi

    - name: Test
      run: go test -v ./...
